# Generated by Django 4.1.2 on 2022-10-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='Song',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Artiste',
            new_name='artiste_id',
        ),
    ]
